---
functional:
  - Должна быть реализована регистрация пользователей
  - Пользователь должен иметь возможность авторизации
  - Пользователь должен иметь возможность редактирования профиля
  - Авторизованный пользователь должен иметь возможность создавать игру
  - У неавторизованного пользователя должна быть возможность создавать игру
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность завершить игру досрочно
  - Пользователь должен иметь возможность восттановить пароль
  - При верном решении, пользователю выводится оповещение о победе
  - Пользователь должен иметь возможность создавать игру с другими пользователями
  - Пользователь должен иметь возможность создавать игру с другом
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт должен обладать возможностью быстрого и простого внесения изменений в функциональность
  - У сайта должна быть интуитивная навигация
  - Сайт должен быть отзывчивым
  - Пользователь должен иметь возможность входа по логину/почте
  - Пользователь должен иметь возможность изменять почту для контактов/рассылки
  - Пользователь должен иметь возможность изменять аватар
  - Пользователь должен иметь возможность просматривать вводимый пароль при входе/регистрации
  - Когда турнир уже создан, он должен выделяться в профиле
  - Авторизованный пользователь должен иметь возможность сменить пароль в настройках профиля
