---
functional:
  - Должна быть реализована регистрация пользователей
  - Пользователь должен иметь возможность авторизации
  - Пользователь должен иметь возможность редактирования профиля
  - Авторизованный пользователь должен иметь возможность создавать игру
  - У неавторизованного пользователя должна быть возможность создавать игру
  - Сайт должен иметь мобильную версию
  - На сайте должен быть критерий выбора игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен обеспечивать защиту персональных данных пользователей
  - Сайт должен работать на различных устройствах и браузерах
  - Сайт должен обеспечивать стабильную работу
implicit:
  - Сайт должен обладать возможностью быстрого и простого внесения изменений в функциональность
  - У сайта должна быть интуитивная навигация
  - Сайт должен быть отзывчивым
  - Пользователь должен иметь возможность входа по логину/почте
  - Пользователь должен иметь возможность изменять почту для контактов/рассылки
  - Пользователь должен иметь возможность изменять аватар
